# Configuration file for custom scenarios for `premise`
# Energy outlook PATHS2050
# https://perspective2050.energyville.be/

---

production pathways:
#1
  biogas:
    production volume:
      variable: Production|Electricity|Renewable|Biogas
    ecoinvent alias:
      name: heat and power co-generation, biogas, gas engine
      reference product: electricity, high voltage
      exists in original database: True

#2
  biomass:
    production volume:
      variable: Production|Electricity|Renewable|Biomass
    ecoinvent alias:
      name: heat and power co-generation, wood chips, 6667 kW, state-of-the-art 2014
      reference product: electricity, high voltage
      exists in original database: True

#3
  bagasse:
    production volume:
      variable: Production|Electricity|Renewable|Bagasse
    ecoinvent alias:
      name: treatment of bagasse, from sweet sorghum, in heat and power co-generation unit, 6400kW thermal
      reference product: electricity, high voltage
      exists in original database: True

#4
  biowaste:
    production volume:
      variable: Production|Electricity|Renewable|Biowaste
    ecoinvent alias:
      name: treatment of biowaste, municipal incineration
      reference product: electricity, for reuse in municipal waste incineration only
      exists in original database: True

#5
  blast_furnace:
    production volume:
      variable: Production|Electricity|Conventional|Blast-furnace
    ecoinvent alias:
      name: treatment of blast furnace gas, in power plant
      reference product: electricity, high voltage
      exists in original database: True

#6
  coal_chp:
    production volume:
      variable: Production|Electricity|Conventional|Coal CHP
    ecoinvent alias:
      name: heat and power co-generation, hard coal
      reference product: electricity, high voltage
      exists in original database: True

#7
  oil_chp:
    production volume:
      variable: Production|Electricity|Conventional|Oil CHP
    ecoinvent alias:
      name: heat and power co-generation, oil
      reference product: electricity, high voltage
      exists in original database: True

#8
  municipal_waste:
    production volume:
      variable: Production|Electricity|Conventional|Municipal waste incineration
    ecoinvent alias:
      name: electricity, from municipal waste incineration to generic market for electricity, medium voltage
      reference product: electricity, medium voltage
      exists in original database: True

#9
  natural_gas_chp_400:
    production volume:
      variable: Production|Electricity|Conventional|Natural gas CHP|400MW electrical
    ecoinvent alias:
      name: heat and power co-generation, natural gas, combined cycle power plant, 400MW electrical
      reference product: electricity, high voltage
      exists in original database: True

#10
  natural_gas_chp_100:
    production volume:
      variable: Production|Electricity|Conventional|Natural gas CHP|100MW electrical
    ecoinvent alias:
      name: heat and power co-generation, natural gas, conventional power plant, 100MW electrical
      reference product: electricity, high voltage
      exists in original database: True

#11
  natural_gas_ppt:
    production volume:
      variable: Production|Electricity|Conventional|Natural gas PPT
    ecoinvent alias:
      name: electricity production, natural gas, combined cycle power plant
      reference product: electricity, high voltage
      exists in original database: True

#12
  oil_chp:
    production volume:
      variable: Production|Electricity|Conventional|Oil CHP
    ecoinvent alias:
      name: heat and power co-generation, oil
      reference product: electricity, high voltage
      exists in original database: True

#13
  oil_ppt:
    production volume:
      variable: Production|Electricity|Conventional|Oil PPT
    ecoinvent alias:
      name: electricity production, oil
      reference product: electricity, high voltage
      exists in original database: True

#14
  coal_gas:
    production volume:
      variable: Production|Electricity|Conventional|Coal gas
    ecoinvent alias:
      name: treatment of coal gas, in power plant
      reference product: electricity, high voltage
      exists in original database: True

#15 - Production|Gaseous fuel|Hydrogen|Domestic|Electrolysis
  electrolysis_hydrogen:
    production volume:
      variable: Production|Gaseous fuel|Hydrogen|Domestic|Electrolysis
    efficiency:
      - variable: Efficiency|Gaseous fuel|Hydrogen|Domestic|Electrolysis
        includes:
          technosphere:
            - electricity
    ecoinvent alias:
        name: hydrogen production, gaseous, 30 bar, from PEM electrolysis, from grid electricity, domestic, PATHS2050
        reference product: hydrogen, gaseous, 30 bar
        exists in original database: TRUE

#16
  nuclear:
    production volume:
      variable: Production|Electricity|Nuclear|Boiling water reactor
    ecoinvent alias:
      name: electricity production, nuclear, pressure water reactor
      reference product: electricity, high voltage
      exists in original database: True

#17

  import:
    production volume:
      variable: Production|Electricity|Import
    ecoinvent alias:
      name: market group for electricity, high voltage
      reference product: electricity, high voltage
      exists in original database: True

#18
  hydro_run_of_river:
    production volume:
      variable: Production|Electricity|Run-of-river hydro
    ecoinvent alias:
      name: electricity production, hydro, pumped storage
      reference product: electricity, high voltage
      exists in original database: True

#19
  hydro_reservoir:
    production volume:
      variable: Production|Electricity|Reservoir
    ecoinvent alias:
      name: electricity production, hydro, run-of-river
      reference product: electricity, high voltage
      exists in original database: True

#20
  pv_570kWp:
    production volume:
      variable: Production|Electricity|Renewable|Photovoltaic|570kWp open ground
    ecoinvent alias:
      name: electricity production, photovoltaic, 570kWp open ground installation, multi-Si
      reference product: electricity, low voltage
      exists in original database: True

#21
  pv_3kWp_single:
    production volume:
      variable: Production|Electricity|Renewable|Photovoltaic|3kWp single-Si
    ecoinvent alias:
      name: electricity production, photovoltaic, 3kWp slanted-roof installation, multi-Si, panel, mounted
      reference product: electricity, low voltage
      exists in original database: True

#22
  pv_3kWp_multi:
    production volume:
      variable: Production|Electricity|Renewable|Photovoltaic|3kWp multi-Si
    ecoinvent alias:
      name: electricity production, photovoltaic, 3kWp slanted-roof installation, single-Si, panel, mounted
      reference product: electricity, low voltage
      exists in original database: True

#23
  wind_offshore:
    production volume:
      variable: Production|Electricity|Renewable|Wind turbines|Offshore
    ecoinvent alias:
      name: electricity production, wind, 1-3MW turbine, offshore
      reference product: electricity, high voltage
      exists in original database: True

#24
  wind_on_1-3:
    production volume:
      variable: Production|Electricity|Renewable|Wind turbines|Onshore|1-3MW
    ecoinvent alias:
      name: electricity production, wind, 1-3MW turbine, onshore
      reference product: electricity, high voltage
      exists in original database: True

#25
  wind_on_1MW:
    production volume:
      variable: Production|Electricity|Renewable|Wind turbines|Onshore|<1MW
    ecoinvent alias:
      name: electricity production, wind, <1MW turbine, onshore
      reference product: electricity, high voltage
      exists in original database: True

#26
  wind_on_3MW:
    production volume:
      variable: Production|Electricity|Renewable|Wind turbines|Onshore|>3MW
    ecoinvent alias:
      name: electricity production, wind, >3MW turbine, onshore
      reference product: electricity, high voltage
      exists in original database: True

#27
  medium_to_high:
    production volume:
      variable: Production|Electricity|Medium to high
    ecoinvent alias:
      name: market for electricity, high voltage, PATHS2050
      reference product: electricity, high voltage
      exists in original database: False
      new dataset: True

#28
  low_to_medium:
    production volume:
      variable: Production|Electricity|Low to medium
    ecoinvent alias:
      name: market for electricity, medium voltage, PATHS2050
      reference product: electricity, medium voltage
      exists in original database: False
      new dataset: True
      
markets:
#  - name: market for hydrogen, gaseous, PATHS2050
#    reference product: hydrogen, gaseous
#    unit: kilogram
#    includes:
#      - electrolysis_hydrogen
#      - electrolysis_hydrogen_import

#    add:

#      - name: solution mining for geological hydrogen storage
#        reference product: solution mining
#        amount: 1.0

#      - name: geological hydrogen storage
#        reference product: hydrogen storage
#        amount: 1.0

#      - name: market for transport, freight, lorry, unspecified
#        reference product: transport, freight, lorry, unspecified
#        amount: 0.2

#      - name: Hydrogen
#        categories: air::non-urban air or from high stacks
#        unit: kilogram
#        amount: 0.01

#    efficiency:
#      - variable: Cushion gas|Gaseous fuel|Hydrogen|Geological storage
#        includes:
#          technosphere:
#            - name: hydrogen production

#    except regions:
#      - World

#  - name: market for hydrogen, liquid, PATHS2050
#    reference product: hydrogen, liquid
#    unit: kilogram
#    includes:
#      - electrolysis_hydrogen

#    add:
#      - name: high pressure hydrogen storage tank
#        reference product: high pressure hydrogen storage tank
#        amount: 1.37e-4

#      - name: market for electricity, low voltage
#        reference product: electricity, low voltage
#        amount: 12.0

#      - name: market for transport, freight, lorry, unspecified
#        reference product: transport, freight, lorry, unspecified
#        amount: 0.2

#      - name: Hydrogen
#        categories: air::non-urban air or from high stacks
#        unit: kilogram
#        amount: 0.01

#    efficiency:
#      - variable: Efficiency|Gaseous fuel|Hydrogen|Liquefaction
#        includes:
#          technosphere:
#            - name: electricity

#      - variable: Distribution losses|Gaseous fuel|Hydrogen|Liquefaction
#        includes:
#          technosphere:
#            - name: hydrogen
#          biosphere:
#            - name: Hydrogen

#      - variable: Distribution losses|Gaseous fuel|Hydrogen|Evaporation
#        includes:
#          technosphere:
#            - name: hydrogen

#      - variable: Distribution losses|Gaseous fuel|Hydrogen|Leakage
#        includes:
#          biosphere:
#              - name: Hydrogen

#    except regions:
#      - World

#    replaces:
#      - name: market for hydrogen, liquid
#        product: hydrogen, liquid

#    replaces in:
#      - location: BE

  - name: market for electricity, high voltage, PATHS2050
    reference product: electricity, high voltage
    unit: kilowatt hour
    includes:
      - biogas
      - biomass
      - bagasse
      - biowaste
      - blast_furnace
      - coal_chp
      - natural_gas_chp_400
      - natural_gas_chp_100
      - natural_gas_ppt
      - oil_chp
      - oil_ppt
      - coal_gas
      - electrolysis_hydrogen
      - nuclear
      - import
      - hydro_run_of_river
      - hydro_reservoir
      - wind_offshore
      - wind_on_1-3
      - wind_on_1MW
      - wind_on_3MW

    add:

      - name: transmission network construction, electricity, high voltage
        reference product: transmission network, electricity, high voltage
        amount: 6.58e-09

      - name: Dinitrogen monoxide
        categories: air
        unit: kilogram
        amount: 5.0e-06

      - name: Ozone
        categories: air
        unit: kilogram
        amount: 4.16e-06

    replaces:
      - name: market for electricity, high voltage
        product: electricity, high voltage
        location: BE

    replaces in:
      - location: BE

    except regions:
      - World

  - name: market for electricity, medium voltage, PATHS2050
    reference product: electricity, medium voltage
    unit: kilowatt hour
    includes:
      - municipal_waste
      - medium_to_high

    add:

      - name: market for sulfur hexafluoride, liquid
        reference product: sulfur hexafluoride, liquid
        amount: 5.4e-08

      - name: transmission network construction, electricity, medium voltage
        reference product: transmission network, electricity, medium voltage
        amount: 1.86e-08

      - name: Sulfur hexafluoride
        categories: air
        unit: kilogram
        amount: 5.4e-08

    replaces:
      - name: market for electricity, medium voltage
        product: electricity, medium voltage
        location: BE

    replaces in:
      - location: BE

    except regions:
      - World

  - name: market for electricity, low voltage, PATHS2050
    reference product: electricity, low voltage
    unit: kilowatt hour
    includes:
      - pv_570kWp
      - pv_3kWp_single
      - pv_3kWp_multi
      - low_to_medium

    add:
      - name: market for sulfur hexafluoride, liquid
        reference product: sulfur hexafluoride, liquid
        amount: 2.99e-09

      - name: distribution network construction, electricity, low voltage
        reference product: distribution network, electricity, low voltage
        amount: 8.74e-08

      - name: Sulfur hexafluoride
        categories: air
        unit: kilogram
        amount: 2.99e-09

    replaces:
      - name: market for electricity, low voltage
        product: electricity, low voltage
        location: BE

    replaces in:
      - location: BE

    except regions:
      - World